import { motion } from "framer-motion";
import { 
  Gem, 
  FileCode, 
  Sparkles, 
  ShieldCheck,
  ArrowRight,
  Bitcoin,
  Code,
  Lock,
  Eye,
} from "lucide-react";

const steps = [
  {
    id: 1,
    title: '"Enchanted" UTXOs',
    description: 'Bitcoin transaction outputs are "enchanted" with Charms data - representing tokens, NFTs, or application state.',
    icon: Gem,
    color: 'from-cyan-500 to-blue-500',
  },
  {
    id: 2,
    title: 'App Contracts',
    description: 'Programmable logic written in Rust and WASM determine how assets can be created, transferred, or modified.',
    icon: FileCode,
    color: 'from-purple-500 to-pink-500',
  },
  {
    id: 3,
    title: 'Spells and Proofs',
    description: 'Transactions include "spells" - metadata with zero-knowledge proofs that verify their correctness without transaction history traversal.',
    icon: Sparkles,
    color: 'from-orange-500 to-yellow-500',
  },
  {
    id: 4,
    title: 'Client-Side Validation',
    description: 'Users verify assets with minimal resources - no indexers, validators, or extensive infrastructure required.',
    icon: ShieldCheck,
    color: 'from-green-500 to-emerald-500',
  },
];

const workflowSteps = [
  { 
    title: 'Spell Creation', 
    description: '"Enchants" transaction outputs with charms tokens.',
    icon: Code,
    color: 'bg-purple-500',
  },
  { 
    title: 'ZK-Proof Generation', 
    description: 'Proves app logic was correctly executed.',
    icon: Lock,
    color: 'bg-cyan-500',
  },
  { 
    title: 'On-chain Storage', 
    description: 'No indexers needed - all necessary information is in the transaction.',
    icon: Bitcoin,
    color: 'bg-orange-500',
  },
];

const useCases = [
  { icon: Bitcoin, title: 'Bitcoin Lending Protocol' },
  { icon: Gem, title: 'Synthetic Assets / Bitcoin Backed Stables' },
  { icon: Code, title: 'Governance Tokens and Contracts' },
];

export function CharmsFlowDiagram() {
  return (
    <div className="space-y-12">
      {/* How Charms Works Section */}
      <section>
        <div className="flex items-center gap-4 mb-8">
          <div className="relative">
            <div className="w-16 h-16 rounded-2xl bg-gradient-to-br from-cyan-500 to-blue-600 flex items-center justify-center">
              <Gem className="w-8 h-8 text-white" />
            </div>
            <div className="absolute -bottom-1 -right-1 w-6 h-6 rounded-full bg-primary animate-pulse" />
          </div>
          <div>
            <h2 className="text-2xl md:text-3xl font-bold text-foreground">How Charms Works</h2>
            <p className="text-muted-foreground">Programmable assets on Bitcoin</p>
          </div>
        </div>

        <div className="space-y-4">
          {steps.map((step, index) => (
            <motion.div
              key={step.id}
              initial={{ opacity: 0, x: -30 }}
              animate={{ opacity: 1, x: 0 }}
              transition={{ delay: index * 0.1 }}
              className="flex gap-4 p-4 rounded-xl bg-card/50 border border-border/50 hover:border-primary/30 transition-all group"
            >
              <div className={`flex-shrink-0 w-12 h-12 rounded-xl bg-gradient-to-br ${step.color} flex items-center justify-center shadow-lg group-hover:scale-110 transition-transform`}>
                <step.icon className="w-6 h-6 text-white" />
              </div>
              <div>
                <h3 className="font-semibold text-foreground mb-1">{step.title}</h3>
                <p className="text-sm text-muted-foreground">{step.description}</p>
              </div>
            </motion.div>
          ))}
        </div>
      </section>

      {/* Spells & zkVM Proofs Section */}
      <section className="p-6 rounded-2xl bg-gradient-to-br from-muted/50 to-muted/30 border border-border/50">
        <h3 className="text-xl font-bold text-foreground mb-2">Spells & zkVM Proofs</h3>
        <p className="text-sm text-muted-foreground mb-6">
          Charms transactions are called "spells." They "enchant" the transaction outputs with charms tokens, 
          and a zk-proof that app logic was correctly executed. Proofs can be generated by anyone via the 
          Charms CLI or proving API.
        </p>
        <p className="text-sm text-muted-foreground mb-8">
          Clients verify transactions and their embedded zk-proofs. All validation is local — no need to 
          traverse the transaction history.
        </p>

        {/* Workflow Steps */}
        <div className="flex flex-col md:flex-row items-stretch gap-4">
          {workflowSteps.map((ws, index) => (
            <motion.div
              key={ws.title}
              initial={{ opacity: 0, y: 20 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ delay: 0.3 + index * 0.1 }}
              className="flex-1 relative"
            >
              <div className="h-full p-4 rounded-xl bg-card border border-border/50">
                <div className={`w-10 h-10 rounded-lg ${ws.color} flex items-center justify-center mb-3`}>
                  <ws.icon className="w-5 h-5 text-white" />
                </div>
                <h4 className="font-semibold text-foreground mb-1">{ws.title}</h4>
                <p className="text-xs text-muted-foreground">{ws.description}</p>
              </div>
              
              {index < workflowSteps.length - 1 && (
                <div className="hidden md:flex absolute right-0 top-1/2 -translate-y-1/2 translate-x-1/2 z-10">
                  <ArrowRight className="w-5 h-5 text-primary" />
                </div>
              )}
            </motion.div>
          ))}
        </div>
      </section>

      {/* Use Cases Section */}
      <section>
        <h3 className="text-xl font-bold text-foreground mb-4">What You Can Build On Charms</h3>
        <div className="space-y-3">
          {useCases.map((uc, index) => (
            <motion.div
              key={uc.title}
              initial={{ opacity: 0, x: -20 }}
              animate={{ opacity: 1, x: 0 }}
              transition={{ delay: 0.5 + index * 0.1 }}
              className="flex items-center gap-3 p-3 rounded-lg bg-card/30 border border-border/30 hover:border-primary/30 transition-colors"
            >
              <div className="w-8 h-8 rounded-lg bg-primary/10 flex items-center justify-center">
                <uc.icon className="w-4 h-4 text-primary" />
              </div>
              <span className="text-sm font-medium text-foreground">{uc.title}</span>
            </motion.div>
          ))}
          <p className="text-xs text-muted-foreground italic pl-11">...you name it.</p>
        </div>
      </section>

      {/* Technical Links */}
      <div className="flex flex-wrap gap-2">
        <a 
          href="https://github.com/CharmsDev" 
          target="_blank" 
          rel="noopener noreferrer"
          className="inline-flex items-center gap-2 px-3 py-1.5 rounded-full bg-muted/50 border border-border/50 hover:border-primary/30 transition-colors text-sm"
        >
          <Code className="w-4 h-4" />
          CharmsDev GitHub
        </a>
        <a 
          href="https://charms.dev" 
          target="_blank" 
          rel="noopener noreferrer"
          className="inline-flex items-center gap-2 px-3 py-1.5 rounded-full bg-muted/50 border border-border/50 hover:border-primary/30 transition-colors text-sm"
        >
          <Eye className="w-4 h-4" />
          Learn More
        </a>
      </div>
    </div>
  );
}
